export const SHOW_LOADING_LOGIN = "SHOW_LOADING_LOGIN";
export const HIDDEN_LOADING_LOGIN = "HIDDEN_LOADING_LOGIN";
export const OPEN_MODAL_PRODUCT = "OPEN_MODAL_ADD_PRODUCT";
export const CLOSE_MODAL_PRODUCT = "CLOSE_MODAL_ADD_PRODUCT";
export const SHOW_LOADING_ADD_PRODUCT = "SHOW_LOADING_ADD_PRODUCT";
export const HIDDEN_LOADING_ADD_PRODUCT = "HIDDEN_LOADING_ADD_PRODUCT";